android_sdk_repository(
    name = "androidsdk",
)

local_repository(
    name = "rules_android_ndk",
    path = "../..",
)

load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")

android_ndk_repository(name = "androidndk")

# Import rules_android

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_ANDROID_COMMIT = "a54904b056250a213117cee9287c996cd042f388"

RULES_ANDROID_SHA = "bf08c364e6d0946d09b485aee388557bba3bdb5f15323f73c2723d07d3503ba6"

http_archive(
    name = "build_bazel_rules_android",
    sha256 = RULES_ANDROID_SHA,
    strip_prefix = "rules_android-%s" % RULES_ANDROID_COMMIT,
    url = "https://github.com/bazelbuild/rules_android/archive/%s.zip" % RULES_ANDROID_COMMIT,
)

load("@build_bazel_rules_android//:prereqs.bzl", "rules_android_prereqs")

rules_android_prereqs()

load("@build_bazel_rules_android//:defs.bzl", "rules_android_workspace")

rules_android_workspace()

register_toolchains(
    "@build_bazel_rules_android//toolchains/android:android_default_toolchain",
    "@build_bazel_rules_android//toolchains/android_sdk:android_sdk_tools",
)
