android_sdk_repository(
    name = "androidsdk",
)

local_repository(
    name = "rules_android_ndk",
    path = "../..",
)

load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")

android_ndk_repository(
    name = "androidndk",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_foreign_cc",
    strip_prefix = "rules_foreign_cc-d33d862abb4ce3ba178547ef58c9fcb24cec38ca",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/d33d862abb4ce3ba178547ef58c9fcb24cec38ca.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

http_archive(
    name = "com_github_facebook_zstd",
    build_file_content = """
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "all",
    srcs = glob(
        include = ["**"],
    ),
)

cmake(
    name = "zstd",
    build_data = [":all"],
    cache_entries = {
        "CMAKE_INSTALL_LIBDIR": "lib",
        "ZSTD_BUILD_SHARED": "off",
        "ZSTD_BUILD_STATIC": "on",
    },
    generate_args = ["-GNinja"],
    generate_crosstool_file = False,
    install = False,
    lib_source = ":all",
    out_static_libs = ["libzstd.a"],
    targets = [
        "",
        "install",
    ],
    working_directory = "build/cmake",
    visibility = ["//visibility:public"],
)
    """,
    strip_prefix = "zstd-a488ba114ec17ea1054b9057c26a046fc122b3b6",
    urls = [
        "https://github.com/facebook/zstd/archive/a488ba114ec17ea1054b9057c26a046fc122b3b6.tar.gz",
    ],
)
